apiVersion: v1
kind: Pod
metadata:
  name: gateway
spec:
  containers:
    - name: app
      image: justman/gateway
      resources:
        requests:
          ephemeral-storage: "2Gi"
        limits:
          ephemeral-storage: "4Gi"
      volumeMounts:
        - name: ephemeral
          mountPath: "/tmp"
  volumes:
    - name: ephemeral
      emptyDir:
        sizeLimit: 500Mi